// Developer Express Code Central Example:
// How to implement the ThemeHelper that populates an existing RibbonGalleryBarItem or any menu with items
// 
// This example demonstrates how to implement the WinForm SkinHelper class
// functionality in WPF applications (ThemeHelper) that populate an existing
// RibbonGalleryBarItem or any menu (PopupMenu or BarSubItem) with items that
// correspond to DevExpress themes. The basic logic is implemented in the
// ThemeHelper class.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4288

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeHelperWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
