' Developer Express Code Central Example:
' How to implement the ThemeHelper that populates an existing RibbonGalleryBarItem or any menu with items
' 
' This example demonstrates how to implement the WinForm SkinHelper class
' functionality in WPF applications (ThemeHelper) that populate an existing
' RibbonGalleryBarItem or any menu (PopupMenu or BarSubItem) with items that
' correspond to DevExpress themes. The basic logic is implemented in the
' ThemeHelper class.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4288
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.544
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace ThemeHelperWPF.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As ThemeHelperWPF.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ThemeHelperWPF.Properties.Settings())), ThemeHelperWPF.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return ThemeHelperWPF.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
